spring:
  application:
    name: productos-service

  datasource:
    url: jdbc:mysql://localhost:3306/productos_service?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka